Correct version files and update bash test scripts

diff --git a/C/H5T/test.sh.in b/C/H5T/test.sh.in
--- a/C/H5T/test.sh.in
+++ b/C/H5T/test.sh.in
@@ -52,9 +52,9 @@ version_compare() {
 H5_LIBVER=@H5_LIBVER@
 H5_LIBVER_DIR=@H5_LIBVER_DIR@
 
-topics="int intatt float floatatt enum enumatt bit bitatt opaque opaqueatt \
-array arrayatt vlen vlenatt string stringatt vlstring vlstringatt \
-cmpd cmpdatt commit"
+topics="array arrayatt bit bitatt cmpd cmpdatt cpxcmpd cpxcmpdatt enum enumatt float floatatt \
+int intatt opaque opaqueatt string stringatt vlstring vlstringatt \
+commit"
 
 return_val=0
 
@@ -63,7 +63,7 @@ do
     fname=h5ex_t_$topic
     $ECHO_N "Testing C/H5T/$fname...$ECHO_C"
     exout ./$fname >tmp.test
-    cmp -s tmp.test $srcdir/tfiles/$H5_LIBVER_DIR/$fname.tst
+    cmp -s tmp.test $srcdir/tfiles/16/$fname.tst
     status=$?
     if test $status -ne 0
     then
@@ -71,7 +71,7 @@ do
     else
         dumpout $fname.h5 >tmp.test
       rm -f $fname.h5
-      cmp -s tmp.test $srcdir/tfiles/$H5_LIBVER_DIR/$fname.ddl
+      cmp -s tmp.test $srcdir/tfiles/18/$fname.ddl
       status=$?
       if test $status -ne 0
       then
@@ -87,7 +87,13 @@ done
 #######Non-standard tests#######
 
 USE_ALT=""
-if [ "$H5_LIBVER_DIR" = "110" ]; then
+if [ "$H5_LIBVER_DIR" = "114" ]; then
+   # check if HDF5 version is < 1.14.3
+   version_compare "$H5_LIBVER" "1.10.3"
+   if [ "$version_lt" = 1 ]; then
+      USE_ALT="02"
+   fi
+elif [ "$H5_LIBVER_DIR" = "110" ]; then
    # check if HDF5 version is < 1.10.7
    version_compare "$H5_LIBVER" "1.10.7"
    if [ "$version_lt" = 1 ]; then
@@ -110,76 +116,72 @@ do
     fname=h5ex_t_$topic
     $ECHO_N "Testing C/H5T/$fname...$ECHO_C"
     exout ./$fname >tmp.test
-    cmp -s tmp.test $srcdir/tfiles/$H5_LIBVER_DIR/$fname.tst
+    cmp -s tmp.test $srcdir/tfiles/16/$fname.tst
     status=$?
     if test $status -ne 0
     then
         echo "  FAILED!"
     else
         dumpout $fname.h5 >tmp.test
-      rm -f $fname.h5
-      cmp -s tmp.test $srcdir/tfiles/$H5_LIBVER_DIR/$fname$USE_ALT.ddl
-      status=$?
-      if test $status -ne 0
-      then
-          echo "  FAILED!"
-      else
-          echo "  Passed"
-      fi
+        rm -f $fname.h5
+        version_compare "$H5_LIBVER" "1.10.0"
+        if [ "$version_lt" = 1 ]; then
+            cmp -s tmp.test $srcdir/tfiles/18/$fname$USE_ALT.ddl
+        else
+            version_compare "$H5_LIBVER" "1.12.0"
+            if [ "$version_lt" = 1 ]; then
+                cmp -s tmp.test $srcdir/tfiles/110/$fname$USE_ALT.ddl
+            else
+                cmp -s tmp.test $srcdir/tfiles/112/$fname.ddl
+            fi
+        fi
+        status=$?
+        if test $status -ne 0
+        then
+            echo "  FAILED!"
+        else
+            echo "  Passed"
+        fi
     fi
     return_val=`expr $status + $return_val`
 done
 
-fname=h5ex_t_cpxcmpd
-$ECHO_N "Testing C/H5T/$fname...$ECHO_C"
-exout ./$fname >tmp.test
-cmp -s tmp.test $srcdir/tfiles/$H5_LIBVER_DIR/$fname.tst
-status=$?
-if test $status -ne 0
-then
-    echo "  FAILED!"
-else
-  dumpout -n $fname.h5 >tmp.test
-  rm -f $fname.h5
-  cmp -s tmp.test $srcdir/tfiles/$H5_LIBVER_DIR/$fname.ddl
-  status=$?
-  if test $status -ne 0
-  then
-      echo "  FAILED!"
-  else
-      echo "  Passed"
-  fi
-fi
-return_val=`expr $status + $return_val`
+topics="vlen vlenatt"
 
-
-fname=h5ex_t_cpxcmpdatt
-$ECHO_N "Testing C/H5T/$fname...$ECHO_C"
-exout ./$fname >tmp.test
-cmp -s tmp.test $srcdir/tfiles/$H5_LIBVER_DIR/$fname.tst
-status=$?
-if test $status -ne 0
-then
-    echo "  FAILED!"
-else
-  dumpout -n $fname.h5 >tmp.test
-  rm -f $fname.h5
-  cmp -s tmp.test $srcdir/tfiles/$H5_LIBVER_DIR/$fname.ddl
-  status=$?
-  if test $status -ne 0
-  then
-      echo "  FAILED!"
-  else
-      echo "  Passed"
-  fi
-fi
-return_val=`expr $status + $return_val`
+for topic in $topics
+do
+    fname=h5ex_t_$topic
+    $ECHO_N "Testing C/H5T/$fname...$ECHO_C"
+    exout ./$fname >tmp.test
+    cmp -s tmp.test $srcdir/tfiles/16/$fname.tst
+    status=$?
+    if test $status -ne 0
+    then
+        echo "  FAILED!"
+    else
+        dumpout -n $fname.h5 >tmp.test
+        rm -f $fname.h5
+        version_compare "$H5_LIBVER" "1.14.0"
+        if [ "$version_lt" = 1 ]; then
+            cmp -s tmp.test $srcdir/tfiles/18/$fname.ddl
+        else
+            cmp -s tmp.test $srcdir/tfiles/114/$fname$USE_ALT.ddl
+        status=$?
+        if test $status -ne 0
+        then
+            echo "  FAILED!"
+        else
+            echo "  Passed"
+        fi
+    fi
+    return_val=`expr $status + $return_val`
+done
 
 
 fname=h5ex_t_convert
 $ECHO_N "Testing C/H5T/$fname...$ECHO_C"
 exout ./$fname >tmp.test
-cmp -s tmp.test $srcdir/tfiles/$H5_LIBVER_DIR/$fname.tst
+cmp -s tmp.test $srcdir/tfiles/16/$fname.tst
 status=$?
 if test $status -ne 0
 then
