added version check in test script

diff --git a/FORTRAN/H5D/test.sh.in b/FORTRAN/H5D/test.sh.in
--- a/FORTRAN/H5D/test.sh.in
+++ b/FORTRAN/H5D/test.sh.in
@@ -40,6 +40,15 @@ dumpout() {
     $H5DUMP $*
 }
 
+# compare current version, required version.
+# returns if cur_ver < req_ver is true.
+version_compare() {
+  version_lt=0
+  if [ ! "$(printf '%s\n' "$1" "$2" | sort -V | head -n1)" = "$2" ]; then
+          version_lt=1
+  fi
+}
+
 H5_LIBVER=@H5_LIBVER@
 H5_LIBVER_DIR=@H5_LIBVER_DIR@
 
@@ -51,7 +60,6 @@ topics="alloc \
   fillval \
   gzip \
   hyper \
-  nbit \
   rdwr \
   soint \
   szip \
@@ -118,6 +126,47 @@ done
 
 #######Non-standard tests#######
 
+USE_ALT=""
+version_compare "$H5_LIBVER" "1.8.23"
+# check if HDF5 version is < 1.8.23
+if [ "$version_lt" = 1 ]; then
+    USE_ALT="22"
+else
+# check if HDF5 version is < 1.10.8
+  version_compare "$H5_LIBVER" "1.10.8"
+  if [ "$version_lt" = 1 ]; then
+    USE_ALT="07"
+  fi
+fi
+
+fname=h5ex_d_nbit
+$ECHO_N "Testing FORTRAN/H5D/$fname...$ECHO_C"
+exout ./$fname >tmp.test
+status=$?
+if test $status -eq 1
+then
+    echo "  Unsupported feature"
+else
+    cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.tst
+    status=$?
+    if test $status -ne 0
+    then
+        echo "  FAILED!"
+    else
+        dumpout $fname.h5 >tmp.test
+        rm -f $fname.h5
+        cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname$USE_ALT.ddl
+        status=$?
+        if test $status -ne 0
+        then
+            echo "  FAILED!"
+        else
+            echo "  Passed"
+        fi
+        return_val=`expr $status + $return_val`
+    fi
+    return_val=`expr $status + $return_val`
+fi
 
 #Remove external data file from h5ex_d_extern
 rm -f h5ex_d_extern.data
