Initial autotools changes

diff --git a/FORTRAN/H5D/test.sh.in b/FORTRAN/H5D/test.sh.in
--- a/FORTRAN/H5D/test.sh.in
+++ b/FORTRAN/H5D/test.sh.in
@@ -40,6 +40,9 @@ dumpout() {
     $H5DUMP $*
 }
 
+H5_LIBVER=@H5_LIBVER@
+H5_LIBVER_DIR=@H5_LIBVER_DIR@
+
 topics="alloc \
   checksum \
   chunk \
@@ -64,14 +67,15 @@ rm -f h5ex_d_extern.data
 for topic in $topics
 do
     fname=h5ex_d_$topic
-    $ECHO_N "Testing 1_10/FORTRAN/H5D/$fname...$ECHO_C"
+    $ECHO_N "Testing C/H5D/$fname...$ECHO_C"
     exout ./$fname >tmp.test
     status=$?
     if test $status -eq 1
     then
         echo "  Unsupported feature"
+        status=0
     else
-        cmp -s tmp.test $srcdir/testfiles/$fname.tst
+        cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.tst
         status=$?
         if test $status -ne 0
         then
@@ -79,12 +83,12 @@ do
         else
           dumpout $fname.h5 >tmp.test
           rm -f $fname.h5
-          cmp -s tmp.test $srcdir/testfiles/$fname.ddl
+          cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.ddl
           status=$?
           if test $status -ne 0
              then 
 	     # test to see if the only difference is because of big-endian and little-endian
-	     \diff tmp.test $srcdir/testfiles/$fname.ddl > tmp.diff
+	     \diff tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.ddl > tmp.diff
              echo " "
              NumOfFinds=`grep -c "DATATYPE" tmp.diff`
              NumOfFinds=`expr $NumOfFinds \* 2`
@@ -115,34 +119,34 @@ rm -f h5ex_d_extern.data
 
 
 fname=h5ex_d_transform
-$ECHO_N "Testing 1_10/FORTRAN/H5D/$fname...$ECHO_C"
+$ECHO_N "Testing FORTRAN/H5D/$fname...$ECHO_C"
 exout ./$fname >tmp.test
 status=$?
 if test $status -eq 1
 then
     echo "  Unsupported feature"
 else
-    cmp -s tmp.test $srcdir/testfiles/$fname.tst
+    cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.tst
     status=$?
     if test $status -ne 0
     then
         echo "  FAILED!"
     else
-      dumpout -n $fname.h5 >tmp.test
-    rm -f $fname.h5
-      cmp -s tmp.test $srcdir/testfiles/$fname.ddl
-    status=$?
-    if test $status -ne 0
-    then
-        echo "  FAILED!"
-    else
-        echo "  Passed"
-    fi
+        dumpout -n $fname.h5 >tmp.test
+        rm -f $fname.h5
+        cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.ddl
+        status=$?
+        if test $status -ne 0
+        then
+            echo "  FAILED!"
+        else
+            echo "  Passed"
+        fi
     fi
     return_val=`expr $status + $return_val`
 fi
 
 
 rm -f tmp.test
-echo "$return_val tests failed in 1_10/FORTRAN/H5D/"
+echo "$return_val tests failed in FORTRAN/H5D/"
 exit $return_val
diff --git a/FORTRAN/H5G/test.sh.in b/FORTRAN/H5G/test.sh.in
--- a/FORTRAN/H5G/test.sh.in
+++ b/FORTRAN/H5G/test.sh.in
@@ -40,16 +40,17 @@ dumpout() {
     $H5DUMP $*
 }
 
-
+H5_LIBVER=@H5_LIBVER@
+H5_LIBVER_DIR=@H5_LIBVER_DIR@
 
 return_val=0
 
 
-$ECHO_N "Testing 1_10/FORTRAN/H5G/h5ex_g_create...$ECHO_C"
+$ECHO_N "Testing FORTRAN/H5G/h5ex_g_create...$ECHO_C"
 ./h5ex_g_create
 dumpout h5ex_g_create.h5 >tmp.test
 rm -f h5ex_g_create.h5
-cmp -s tmp.test $srcdir/testfiles/h5ex_g_create.ddl
+cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/h5ex_g_create.ddl
 status=$?
 if test $status -ne 0
 then
@@ -60,33 +61,33 @@ fi
 return_val=`expr $status + $return_val`
 
 
-$ECHO_N "Testing 1_10/FORTRAN/H5G/h5ex_g_compact...$ECHO_C"
+$ECHO_N "Testing FORTRAN/H5G/h5ex_g_compact...$ECHO_C"
 ./h5ex_g_compact >/dev/null
 dumpout h5ex_g_compact1.h5 >tmp.test
-cmp -s tmp.test $srcdir/testfiles/h5ex_g_compact1.ddl
+cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/h5ex_g_compact1.ddl
 status=$?
 if test $status -ne 0
 then
     echo "  FAILED!"
 else
   dumpout h5ex_g_compact2.h5 >tmp.test
-  cmp -s tmp.test $srcdir/testfiles/h5ex_g_compact2.ddl
-status=$?
-if test $status -ne 0
-then
-    echo "  FAILED!"
-else
-    echo "  Passed"
-fi
+  cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/h5ex_g_compact2.ddl
+  status=$?
+  if test $status -ne 0
+  then
+      echo "  FAILED!"
+  else
+      echo "  Passed"
+  fi
 fi
 return_val=`expr $status + $return_val`
 rm -f h5ex_g_compact1.h5
 rm -f h5ex_g_compact2.h5
 
 
-$ECHO_N "Testing 1_10/FORTRAN/H5G/h5ex_g_phase...$ECHO_C"
+$ECHO_N "Testing FORTRAN/H5G/h5ex_g_phase...$ECHO_C"
 exout ./h5ex_g_phase >tmp.test
-cmp -s tmp.test $srcdir/testfiles/h5ex_g_phase.tst
+cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/h5ex_g_phase.tst
 status=$?
 if test $status -ne 0
 then
@@ -98,9 +99,9 @@ return_val=`expr $status + $return_val`
 rm -f h5ex_g_phase.h5
 
 
-$ECHO_N "Testing 1_10/FORTRAN/H5G/h5ex_g_corder...$ECHO_C"
+$ECHO_N "Testing FORTRAN/H5G/h5ex_g_corder...$ECHO_C"
 exout ./h5ex_g_corder >tmp.test
-cmp -s tmp.test $srcdir/testfiles/h5ex_g_corder.tst
+cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/h5ex_g_corder.tst
 status=$?
 if test $status -ne 0
 then
@@ -113,5 +114,5 @@ rm -f h5ex_g_corder.h5
 
 
 rm -f tmp.test
-echo "$return_val tests failed in 1_10/FORTRAN/H5G/"
+echo "$return_val tests failed in /FORTRAN/H5G/"
 exit $return_val
diff --git a/FORTRAN/H5T/test.sh.in b/FORTRAN/H5T/test.sh.in
--- a/FORTRAN/H5T/test.sh.in
+++ b/FORTRAN/H5T/test.sh.in
@@ -40,6 +40,8 @@ dumpout() {
     $H5DUMP $*
 }
 
+H5_LIBVER=@H5_LIBVER@
+H5_LIBVER_DIR=@H5_LIBVER_DIR@
 
 topics="arrayatt_F03 array_F03 bitatt_F03 bit_F03 cmpdatt_F03 cmpd_F03 \
 Cstring_F03 enumatt_F03 enum_F03 floatatt_F03 float_F03 \
@@ -52,24 +54,24 @@ return_val=0
 for topic in $topics
 do
     fname=h5ex_t_$topic
-    $ECHO_N "Testing 1_10/FORTRAN/H5T/$fname...$ECHO_C"
+    $ECHO_N "Testing FORTRAN/H5T/$fname...$ECHO_C"
     exout ./$fname >tmp.test
-    cmp -s tmp.test $srcdir/testfiles/$fname.tst
+    cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.tst
     status=$?
     if test $status -ne 0
     then
         echo "  FAILED!"
     else
         dumpout $fname.h5 >tmp.test
-    rm -f $fname.h5
-      cmp -s tmp.test $srcdir/testfiles/$fname.ddl
-    status=$?
-    if test $status -ne 0
-    then
-        echo "  FAILED!"
-    else
-        echo "  Passed"
-    fi
+      rm -f $fname.h5
+      cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.ddl
+      status=$?
+      if test $status -ne 0
+      then
+          echo "  FAILED!"
+      else
+          echo "  Passed"
+      fi
     fi
     return_val=`expr $status + $return_val`
 done
@@ -78,9 +80,9 @@ done
 #######Non-standard tests#######
 
 #fname=h5ex_t_cpxcmpd
-#$ECHO_N "Testing 1_10/C/H5T/$fname...$ECHO_C"
+#$ECHO_N "Testing FORTRAN/H5T/$fname...$ECHO_C"
 #exout ./$fname >tmp.test
-#cmp -s tmp.test $srcdir/testfiles/$fname.tst
+#cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.tst
 #status=$?
 #if test $status -ne 0
 #then
@@ -88,7 +90,7 @@ done
 #else
 #  dumpout -n $fname.h5 >tmp.test
 #rm -f $fname.h5
-#  cmp -s tmp.test $srcdir/testfiles/$fname.ddl
+#  cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.ddl
 #status=$?
 #if test $status -ne 0
 #then
@@ -101,9 +103,9 @@ done
 
 
 #fname=h5ex_t_cpxcmpdatt
-#$ECHO_N "Testing 1_10/C/H5T/$fname...$ECHO_C"
+#$ECHO_N "Testing FORTRAN/H5T/$fname...$ECHO_C"
 #exout ./$fname >tmp.test
-#cmp -s tmp.test $srcdir/testfiles/$fname.tst
+#cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.tst
 #status=$?
 #if test $status -ne 0
 #then
@@ -111,7 +113,7 @@ done
 #else
 #  dumpout -n $fname.h5 >tmp.test
 #rm -f $fname.h5
-#  cmp -s tmp.test $srcdir/testfiles/$fname.ddl
+#  cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.ddl
 #status=$?
 #if test $status -ne 0
 #then
@@ -124,9 +126,9 @@ done
 
 
 #fname=h5ex_t_convert
-#$ECHO_N "Testing 1_10/C/H5T/$fname...$ECHO_C"
+#$ECHO_N "Testing FORTRAN/H5T/$fname...$ECHO_C"
 #exout ./$fname >tmp.test
-#cmp -s tmp.test $srcdir/$fname.test
+#cmp -s tmp.test $srcdir/testfiles/$H5_LIBVER_DIR/$fname.test
 #status=$?
 #if test $status -ne 0
 #then
@@ -138,5 +140,5 @@ done
 
 
 rm -f tmp.test
-echo "$return_val tests failed in 1_10/FORTRAN/H5T/"
+echo "$return_val tests failed in /FORTRAN/H5T/"
 exit $return_val
