Added 1.8 datasets examples. Added copyright notices to some files. Made shell scripts more portable.
Tested: kagiso, smirom, linew, cygwin

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,7 +273,7 @@ PACKAGE_VERSION='0.1'
 PACKAGE_STRING='HDF5-examples 0.1'
 PACKAGE_BUGREPORT='nfortne2@hdfgroup.org'
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE V16_TRUE V16_FALSE V18_TRUE V18_FALSE H5G_TRUE H5G_FALSE H5T_TRUE H5T_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE V16_TRUE V16_FALSE V18_TRUE V18_FALSE H5G_TRUE H5G_FALSE H5D_TRUE H5D_FALSE H5T_TRUE H5T_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -2732,9 +2732,10 @@ else
 fi
 
 
-if test ! "$H5EX_G" && test ! "$H5EX_T"
+if test ! "$H5EX_G" && test ! "$H5EX_D" && test ! "$H5EX_T"
 then
 	H5EX_G=1
+	H5EX_D=1
 	H5EX_T=1
 fi
 
@@ -2749,6 +2750,16 @@ fi
 
 
 
+if test "$H5EX_D"; then
+  H5D_TRUE=
+  H5D_FALSE='#'
+else
+  H5D_TRUE='#'
+  H5D_FALSE=
+fi
+
+
+
 if test "$H5EX_T"; then
   H5T_TRUE=
   H5T_FALSE='#'
@@ -2759,7 +2770,7 @@ fi
 
 
 # Set subdirectories
-                                                                                          ac_config_files="$ac_config_files makefile 1_6/makefile 1_6/C/makefile 1_6/C/H5G/makefile 1_6/C/H5T/makefile 1_8/makefile 1_8/C/makefile 1_8/C/H5G/makefile 1_8/C/H5T/makefile"
+                                                                                                    ac_config_files="$ac_config_files makefile 1_6/makefile 1_6/C/makefile 1_6/C/H5G/makefile 1_6/C/H5T/makefile 1_8/makefile 1_8/C/makefile 1_8/C/H5G/makefile 1_8/C/H5D/makefile 1_8/C/H5T/makefile"
 
 
 # Configure
@@ -2917,6 +2928,13 @@ if test -z "${H5G_TRUE}" && test -z "${H5G_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"H5G\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"H5G\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${H5D_TRUE}" && test -z "${H5D_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"H5D\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"H5D\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -3374,6 +3392,7 @@ do
   "1_8/makefile" ) CONFIG_FILES="$CONFIG_FILES 1_8/makefile" ;;
   "1_8/C/makefile" ) CONFIG_FILES="$CONFIG_FILES 1_8/C/makefile" ;;
   "1_8/C/H5G/makefile" ) CONFIG_FILES="$CONFIG_FILES 1_8/C/H5G/makefile" ;;
+  "1_8/C/H5D/makefile" ) CONFIG_FILES="$CONFIG_FILES 1_8/C/H5D/makefile" ;;
   "1_8/C/H5T/makefile" ) CONFIG_FILES="$CONFIG_FILES 1_8/C/H5T/makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -3504,6 +3523,8 @@ s,@V18_TRUE@,$V18_TRUE,;t t
 s,@V18_FALSE@,$V18_FALSE,;t t
 s,@H5G_TRUE@,$H5G_TRUE,;t t
 s,@H5G_FALSE@,$H5G_FALSE,;t t
+s,@H5D_TRUE@,$H5D_TRUE,;t t
+s,@H5D_FALSE@,$H5D_FALSE,;t t
 s,@H5T_TRUE@,$H5T_TRUE,;t t
 s,@H5T_FALSE@,$H5T_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
