fixed failures

diff --git a/vers/1_8/FORTRAN/H5T/test.sh.in b/vers/1_8/FORTRAN/H5T/test.sh.in
--- a/vers/1_8/FORTRAN/H5T/test.sh.in
+++ b/vers/1_8/FORTRAN/H5T/test.sh.in
@@ -15,6 +15,7 @@
 
 srcdir=@srcdir@
 
+VER_DIR=$(echo $(basename $(dirname $(dirname $PWD))))
 
 case $FC in
 */*)    H5DUMP=`echo $FC | sed -e 's/\/[^/]*$/\/h5dump/'`;
@@ -45,8 +46,8 @@ topics="vlstring"
 topicsf03="$topics arrayatt_F03 array_F03 bitatt_F03 bit_F03 \
   cmpdatt_F03 cmpd_F03  enumatt_F03 \
   enum_F03 floatatt_F03 float_F03 intatt_F03 int_F03 \
-  objrefatt_F03 objref_F03 opaqueatt_F03 opaque_F03 \
-  regrefatt_F03 regref_F03 stringCatt_F03 stringC_F03 \
+  opaqueatt_F03 opaque_F03 \
+  stringCatt_F03 stringC_F03 \
   string_F03 vlenatt_F03 vlen_F03"
 
 if ($FC -showconfig 2>&1 | grep 'Fortran 2003 Compiler: yes') > /dev/null; then
@@ -67,7 +68,7 @@ return_val=0
 for topic in $topics
 do
     fname=h5ex_t_$topic
-    $ECHO_N "Testing 1_8/FORTRAN/H5T/$fname...$ECHO_C"
+    $ECHO_N "Testing $VER_DIR/FORTRAN/H5T/$fname...$ECHO_C"
     exout ./$fname >tmp.test
     cmp -s tmp.test $srcdir/testfiles/$fname.tst
     status=$?
@@ -78,6 +79,44 @@ do
         dumpout $fname.h5 >tmp.test
       rm -f $fname.h5
       cmp -s tmp.test $srcdir/testfiles/$fname.ddl
+      status=$?
+      if test $status -ne 0
+      then
+          echo "  FAILED!"
+      else
+          echo "  Passed"
+      fi
+    fi
+    return_val=`expr $status + $return_val`
+done
+
+topics="objrefatt_F03 objref_F03 \
+  regrefatt_F03 regref_F03"
+
+VERS=""
+CHCK_HDF5VER=`$FC -showconfig | grep -i "HDF5 Version:" | sed 's/^.* //g' | sed 's/[-].*//g'`
+function version_gt {
+     test "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1"; 
+}
+if version_gt $CHCK_HDF5VER "1.8"; then
+   VERS="110"  
+fi
+
+return_val=0
+for topic in $topics
+do
+    fname=h5ex_t_$topic
+    $ECHO_N "Testing $VER_DIR/FORTRAN/H5T/$fname...$ECHO_C"
+    exout ./$fname >tmp.test
+    cmp -s tmp.test $srcdir/testfiles/$fname.tst
+    status=$?
+    if test $status -ne 0
+    then
+        echo "  FAILED!"
+    else
+      dumpout $fname.h5 >tmp.test
+      rm -f $fname.h5
+      cmp -s tmp.test $srcdir/testfiles/$fname$VERS.ddl
       status=$?
       if test $status -ne 0
       then
@@ -153,5 +192,5 @@ done
 
 
 rm -f tmp.test
-echo "$return_val tests failed in 1_8/FORTRAN/H5T/"
+echo "$return_val tests failed in $VER_DIR/FORTRAN/H5T/"
 exit $return_val
