Convert test.sh files to test.sh.in files

diff --git a/1_10/FORTRAN/H5D/test.sh.in b/1_10/FORTRAN/H5D/test.sh.in
--- a/1_10/FORTRAN/H5D/test.sh.in
+++ b/1_10/FORTRAN/H5D/test.sh.in
@@ -13,6 +13,8 @@
 # http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
 # access to either file, you may request a copy from help@hdfgroup.org.
 
+srcdir=@srcdir@
+
 
 case $FC in
 */*)    H5DUMP=`echo $FC | sed -e 's/\/[^/]*$/\/h5dump/'`;
@@ -39,12 +41,10 @@ dumpout() {
 }
 
 
+
 topics="rdwr hyper chunk gzip  extern compact \
 unlimmod  checksum  fillval alloc"
 
-if ($FC -showconfig 2>&1 | grep 'Fortran 2003 Compiler: yes') > /dev/null; then
-  topics="$topics rdwr_kind_F03"
-fi
 
 return_val=0
 
@@ -52,7 +52,7 @@ return_val=0
 for topic in $topics
 do
     fname=h5ex_d_$topic
-    $ECHO_N "Testing 1_8/FORTRAN/H5D/$fname...$ECHO_C"
+    $ECHO_N "Testing 1_10/FORTRAN/H5D/$fname...$ECHO_C"
     exout ./$fname >tmp.test
     status=$?
     if test $status -eq 1
@@ -103,7 +103,7 @@ rm -f h5ex_d_extern.data
 
 
 fname=h5ex_d_transform
-$ECHO_N "Testing 1_8/FORTRAN/H5D/$fname...$ECHO_C"
+$ECHO_N "Testing 1_10/FORTRAN/H5D/$fname...$ECHO_C"
 exout ./$fname >tmp.test
 status=$?
 if test $status -eq 1
@@ -117,20 +117,20 @@ else
         echo "  FAILED!"
     else
       dumpout -n $fname.h5 >tmp.test
-      rm -f $fname.h5
+    rm -f $fname.h5
       cmp -s tmp.test $srcdir/testfiles/$fname.ddl
-      status=$?
-      if test $status -ne 0
-      then
-          echo "  FAILED!"
-      else
-          echo "  Passed"
-      fi
+    status=$?
+    if test $status -ne 0
+    then
+        echo "  FAILED!"
+    else
+        echo "  Passed"
+    fi
     fi
     return_val=`expr $status + $return_val`
 fi
 
 
 rm -f tmp.test
-echo "$return_val tests failed in 1_8/FORTRAN/H5D/"
+echo "$return_val tests failed in 1_10/FORTRAN/H5D/"
 exit $return_val
diff --git a/1_6/C/H5G/test.sh.in b/1_6/C/H5G/test.sh.in
--- a/1_6/C/H5G/test.sh.in
+++ b/1_6/C/H5G/test.sh.in
@@ -13,6 +13,8 @@
 # http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
 # access to either file, you may request a copy from help@hdfgroup.org.
 
+srcdir=@srcdir@
+
 
 case $CC in
 */*)    H5DUMP=`echo $CC | sed -e 's/\/[^/]*$/\/h5dump/'`;
@@ -57,45 +59,64 @@ dumpout2() {
 }
 
 
-topics="rdwr hyper chunk gzip szip extern compact unlimadd unlimmod unlimgzip \
-checksum shuffle fillval alloc"
-
-
 return_val=0
 
 
-for topic in $topics
-do
-    fname=h5ex_d_$topic
-    $ECHO_N "Testing 1_6/C/H5D/$fname...$ECHO_C"
-    exout ./$fname >tmp.test
-    status=$?
-    if test $status -eq 1
-    then
-        echo "  Unsupported feature"
-    else
-        dumpout2 $fname.h5 >>tmp.test
-        rm -f $fname.h5
-        cmp -s tmp.test $srcdir/$fname.test
-        status=$?
-        if test $status -ne 0
-        then
-            echo "  FAILED!"
-        else
-            echo "  Passed"
-        fi
-        return_val=`expr $status + $return_val`
-    fi
-done
+$ECHO_N "Testing 1_6/C/H5G/h5ex_g_create...$ECHO_C"
+./h5ex_g_create
+dumpout h5ex_g_create.h5 >tmp.test
+rm -f h5ex_g_create.h5
+cmp -s tmp.test $srcdir/h5ex_g_create.test
+status=$?
+if test $status -ne 0
+then
+    echo "  FAILED!"
+else
+    echo "  Passed"
+fi
+return_val=`expr $status + $return_val`
 
 
-#######Non-standard tests#######
+$ECHO_N "Testing 1_6/C/H5G/h5ex_g_iterate...$ECHO_C"
+if test -f "h5ex_g_iterate.h5"
+then
+    exout ./h5ex_g_iterate >tmp.test
+else
+    cp $srcdir/h5ex_g_iterate.h5 h5ex_g_iterate.h5
+    exout ./h5ex_g_iterate >tmp.test
+    rm  -f h5ex_g_iterate.h5
+fi
+cmp -s tmp.test $srcdir/h5ex_g_iterate.test
+status=$?
+if test $status -ne 0
+then
+    echo "  FAILED!"
+else
+    echo "  Passed"
+fi
+return_val=`expr $status + $return_val`
 
 
-#Remove external data file from h5ex_d_extern
-rm -f h5ex_d_extern.data
+$ECHO_N "Testing 1_6/C/H5G/h5ex_g_traverse...$ECHO_C"
+if test -f h5ex_g_traverse.h5
+then
+    exout ./h5ex_g_traverse >tmp.test
+else
+    cp $srcdir/h5ex_g_traverse.h5 h5ex_g_traverse.h5
+    exout ./h5ex_g_traverse >tmp.test
+    rm  -f h5ex_g_traverse.h5
+fi
+cmp -s tmp.test $srcdir/h5ex_g_traverse.test
+status=$?
+if test $status -ne 0
+then
+    echo "  FAILED!"
+else
+    echo "  Passed"
+fi
+return_val=`expr $status + $return_val`
 
 
 rm -f tmp.test
-echo "$return_val tests failed in 1_6/C/H5D/"
+echo "$return_val tests failed in 1_6/C/H5G/"
 exit $return_val
diff --git a/1_8/C/H5D/test.sh.in b/1_8/C/H5D/test.sh.in
--- a/1_8/C/H5D/test.sh.in
+++ b/1_8/C/H5D/test.sh.in
@@ -13,9 +13,11 @@
 # http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
 # access to either file, you may request a copy from help@hdfgroup.org.
 
+srcdir=@srcdir@
 
-case $FC in
-*/*)    H5DUMP=`echo $FC | sed -e 's/\/[^/]*$/\/h5dump/'`;
+
+case $CC in
+*/*)    H5DUMP=`echo $CC | sed -e 's/\/[^/]*$/\/h5dump/'`;
         test -x $H5DUMP || H5DUMP=h5dump;;
 *)      H5DUMP=h5dump;;
 esac
@@ -39,9 +41,8 @@ dumpout() {
 }
 
 
-
-topics="rdwr hyper chunk gzip  extern compact \
-unlimmod  checksum  fillval alloc"
+topics="rdwr hyper chunk gzip szip nbit soint sofloat extern compact unlimadd \
+unlimmod unlimgzip checksum shuffle fillval alloc"
 
 
 return_val=0
@@ -50,7 +51,7 @@ return_val=0
 for topic in $topics
 do
     fname=h5ex_d_$topic
-    $ECHO_N "Testing 1_10/FORTRAN/H5D/$fname...$ECHO_C"
+    $ECHO_N "Testing 1_8/C/H5D/$fname...$ECHO_C"
     exout ./$fname >tmp.test
     status=$?
     if test $status -eq 1
@@ -68,27 +69,13 @@ do
           cmp -s tmp.test $srcdir/testfiles/$fname.ddl
           status=$?
           if test $status -ne 0
-             then 
-	     # test to see if the only difference is because of big-endian and little-endian
-	     \diff tmp.test $srcdir/testfiles/$fname.ddl > tmp.diff
-             echo " "
-             NumOfFinds=`grep -c "DATATYPE" tmp.diff`
-             NumOfFinds=`expr $NumOfFinds \* 2`
-             NumOfLines=`wc -l <tmp.diff`
-             rm -f tmp.diff
-             if test $NumOfLines -gt $NumOfFinds 
-             then
-                echo "  FAILED!"
-	        return_val=`expr $status + $return_val`
-             else
-                echo "  *Inconsequential differance* ... Passed"
-		return_val=`expr $return_val`
-             fi
+          then
+              echo "  FAILED!"
           else
               echo "  Passed"
-	      return_val=`expr $status + $return_val`
           fi
         fi
+        return_val=`expr $status + $return_val`
     fi
 done
 
@@ -101,7 +88,7 @@ rm -f h5ex_d_extern.data
 
 
 fname=h5ex_d_transform
-$ECHO_N "Testing 1_10/FORTRAN/H5D/$fname...$ECHO_C"
+$ECHO_N "Testing 1_8/C/H5D/$fname...$ECHO_C"
 exout ./$fname >tmp.test
 status=$?
 if test $status -eq 1
@@ -114,21 +101,22 @@ else
     then
         echo "  FAILED!"
     else
-      dumpout -n $fname.h5 >tmp.test
-    rm -f $fname.h5
-      cmp -s tmp.test $srcdir/testfiles/$fname.ddl
-    status=$?
-    if test $status -ne 0
-    then
-        echo "  FAILED!"
-    else
-        echo "  Passed"
-    fi
+        dumpout -n $fname.h5 >tmp.test
+        rm -f $fname.h5
+        cmp -s tmp.test $srcdir/testfiles/$fname.ddl
+        status=$?
+        if test $status -ne 0
+        then
+            echo "  FAILED!"
+        else
+            echo "  Passed"
+        fi
+        return_val=`expr $status + $return_val`
     fi
     return_val=`expr $status + $return_val`
 fi
 
 
 rm -f tmp.test
-echo "$return_val tests failed in 1_10/FORTRAN/H5D/"
+echo "$return_val tests failed in 1_8/C/H5D/"
 exit $return_val
diff --git a/1_8/C/H5T/test.sh.in b/1_8/C/H5T/test.sh.in
--- a/1_8/C/H5T/test.sh.in
+++ b/1_8/C/H5T/test.sh.in
@@ -13,6 +13,8 @@
 # http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
 # access to either file, you may request a copy from help@hdfgroup.org.
 
+srcdir=@srcdir@
+
 
 case $CC in
 */*)    H5DUMP=`echo $CC | sed -e 's/\/[^/]*$/\/h5dump/'`;
@@ -31,28 +33,10 @@ ECHO_N="echo $ECHO_N"
 
 
 exout() {
-    echo '*******************************'
-    echo '*  Output of example program  *'
-    echo '*******************************'
-    echo
     $*
 }
 
 dumpout() {
-    echo '**********************'
-    echo '*  Output of h5dump  *'
-    echo '**********************'
-    echo
-    $H5DUMP $*
-}
-
-dumpout2() {
-    echo
-    echo
-    echo '**********************'
-    echo '*  Output of h5dump  *'
-    echo '**********************'
-    echo
     $H5DUMP $*
 }
 
@@ -68,17 +52,24 @@ return_val=0
 for topic in $topics
 do
     fname=h5ex_t_$topic
-    $ECHO_N "Testing 1_6/C/H5T/$fname...$ECHO_C"
+    $ECHO_N "Testing 1_8/C/H5T/$fname...$ECHO_C"
     exout ./$fname >tmp.test
-    dumpout2 $fname.h5 >>tmp.test
-    rm -f $fname.h5
-    cmp -s tmp.test $srcdir/$fname.test
+    cmp -s tmp.test $srcdir/testfiles/$fname.tst
     status=$?
     if test $status -ne 0
     then
         echo "  FAILED!"
     else
-        echo "  Passed"
+        dumpout $fname.h5 >tmp.test
+      rm -f $fname.h5
+      cmp -s tmp.test $srcdir/testfiles/$fname.ddl
+      status=$?
+      if test $status -ne 0
+      then
+          echo "  FAILED!"
+      else
+          echo "  Passed"
+      fi
     fi
     return_val=`expr $status + $return_val`
 done
@@ -87,41 +78,55 @@ done
 #######Non-standard tests#######
 
 fname=h5ex_t_cpxcmpd
-$ECHO_N "Testing 1_6/C/H5T/$fname...$ECHO_C"
+$ECHO_N "Testing 1_8/C/H5T/$fname...$ECHO_C"
 exout ./$fname >tmp.test
-dumpout2 -n $fname.h5 >>tmp.test
-rm -f $fname.h5
-cmp -s tmp.test $srcdir/$fname.test
+cmp -s tmp.test $srcdir/testfiles/$fname.tst
 status=$?
 if test $status -ne 0
 then
     echo "  FAILED!"
 else
-    echo "  Passed"
+  dumpout -n $fname.h5 >tmp.test
+  rm -f $fname.h5
+  cmp -s tmp.test $srcdir/testfiles/$fname.ddl
+  status=$?
+  if test $status -ne 0
+  then
+      echo "  FAILED!"
+  else
+      echo "  Passed"
+  fi
 fi
 return_val=`expr $status + $return_val`
 
 
 fname=h5ex_t_cpxcmpdatt
-$ECHO_N "Testing 1_6/C/H5T/$fname...$ECHO_C"
+$ECHO_N "Testing 1_8/C/H5T/$fname...$ECHO_C"
 exout ./$fname >tmp.test
-dumpout2 -n $fname.h5 >>tmp.test
-rm -f $fname.h5
-cmp -s tmp.test $srcdir/$fname.test
+cmp -s tmp.test $srcdir/testfiles/$fname.tst
 status=$?
 if test $status -ne 0
 then
     echo "  FAILED!"
 else
-    echo "  Passed"
+  dumpout -n $fname.h5 >tmp.test
+  rm -f $fname.h5
+  cmp -s tmp.test $srcdir/testfiles/$fname.ddl
+  status=$?
+  if test $status -ne 0
+  then
+      echo "  FAILED!"
+  else
+      echo "  Passed"
+  fi
 fi
 return_val=`expr $status + $return_val`
 
 
 fname=h5ex_t_convert
-$ECHO_N "Testing 1_6/C/H5T/$fname...$ECHO_C"
+$ECHO_N "Testing 1_8/C/H5T/$fname...$ECHO_C"
 exout ./$fname >tmp.test
-cmp -s tmp.test $srcdir/$fname.test
+cmp -s tmp.test $srcdir/testfiles/$fname.tst
 status=$?
 if test $status -ne 0
 then
@@ -133,5 +138,5 @@ return_val=`expr $status + $return_val`
 
 
 rm -f tmp.test
-echo "$return_val tests failed in 1_6/C/H5T/"
+echo "$return_val tests failed in 1_8/C/H5T/"
 exit $return_val
diff --git a/1_8/FORTRAN/H5G/test.sh.in b/1_8/FORTRAN/H5G/test.sh.in
--- a/1_8/FORTRAN/H5G/test.sh.in
+++ b/1_8/FORTRAN/H5G/test.sh.in
@@ -13,6 +13,8 @@
 # http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
 # access to either file, you may request a copy from help@hdfgroup.org.
 
+srcdir=@srcdir@
+
 
 case $FC in
 */*)    H5DUMP=`echo $FC | sed -e 's/\/[^/]*$/\/h5dump/'`;
@@ -39,11 +41,10 @@ dumpout() {
 }
 
 
-
 return_val=0
 
 
-$ECHO_N "Testing 1_10/FORTRAN/H5G/h5ex_g_create...$ECHO_C"
+$ECHO_N "Testing 1_8/FORTRAN/H5G/h5ex_g_create...$ECHO_C"
 ./h5ex_g_create
 dumpout h5ex_g_create.h5 >tmp.test
 rm -f h5ex_g_create.h5
@@ -58,7 +59,7 @@ fi
 return_val=`expr $status + $return_val`
 
 
-$ECHO_N "Testing 1_10/FORTRAN/H5G/h5ex_g_compact...$ECHO_C"
+$ECHO_N "Testing 1_8/FORTRAN/H5G/h5ex_g_compact...$ECHO_C"
 ./h5ex_g_compact >/dev/null
 dumpout h5ex_g_compact1.h5 >tmp.test
 cmp -s tmp.test $srcdir/testfiles/h5ex_g_compact1.ddl
@@ -69,20 +70,20 @@ then
 else
   dumpout h5ex_g_compact2.h5 >tmp.test
   cmp -s tmp.test $srcdir/testfiles/h5ex_g_compact2.ddl
-status=$?
-if test $status -ne 0
-then
-    echo "  FAILED!"
-else
-    echo "  Passed"
-fi
+  status=$?
+  if test $status -ne 0
+  then
+      echo "  FAILED!"
+  else
+      echo "  Passed"
+  fi
 fi
 return_val=`expr $status + $return_val`
 rm -f h5ex_g_compact1.h5
 rm -f h5ex_g_compact2.h5
 
 
-$ECHO_N "Testing 1_10/FORTRAN/H5G/h5ex_g_phase...$ECHO_C"
+$ECHO_N "Testing 1_8/FORTRAN/H5G/h5ex_g_phase...$ECHO_C"
 exout ./h5ex_g_phase >tmp.test
 cmp -s tmp.test $srcdir/testfiles/h5ex_g_phase.tst
 status=$?
@@ -96,7 +97,7 @@ return_val=`expr $status + $return_val`
 rm -f h5ex_g_phase.h5
 
 
-$ECHO_N "Testing 1_10/FORTRAN/H5G/h5ex_g_corder...$ECHO_C"
+$ECHO_N "Testing 1_8/FORTRAN/H5G/h5ex_g_corder...$ECHO_C"
 exout ./h5ex_g_corder >tmp.test
 cmp -s tmp.test $srcdir/testfiles/h5ex_g_corder.tst
 status=$?
@@ -109,7 +110,71 @@ fi
 return_val=`expr $status + $return_val`
 rm -f h5ex_g_corder.h5
 
+if ($FC -showconfig 2>&1 | grep 'Fortran 2003 Compiler: yes') > /dev/null; then
+
+$ECHO_N "Testing 1_8/FORTRAN/H5G/h5ex_g_iterate_F03...$ECHO_C"
+if test -f h5ex_g_iterate.h5
+then
+    exout ./h5ex_g_iterate_F03 >tmp.test
+else
+    cp $srcdir/h5ex_g_iterate.h5 h5ex_g_iterate.h5
+    exout ./h5ex_g_iterate_F03 >tmp.test
+    rm  -f h5ex_g_iterate.h5
+fi
+cmp -s tmp.test $srcdir/testfiles/h5ex_g_iterate_F03.tst
+status=$?
+if test $status -ne 0
+then
+    echo "  FAILED!"
+else
+    echo "  Passed"
+fi
+return_val=`expr $status + $return_val`
+
+if test -f ./h5ex_g_traverse_F03
+then
+
+  $ECHO_N "Testing 1_8/FORTRAN/H5G/h5ex_g_traverse_F03...$ECHO_C"
+  if test -f h5ex_g_traverse.h5
+  then
+      exout ./h5ex_g_traverse_F03 >tmp.test
+  else
+      cp $srcdir/h5ex_g_traverse.h5 h5ex_g_traverse.h5
+      exout ./h5ex_g_traverse_F03 >tmp.test
+      rm  -f h5ex_g_traverse.h5
+  fi
+  cmp -s tmp.test $srcdir/testfiles/h5ex_g_traverse_F03.tst
+  status=$?
+  if test $status -ne 0
+  then
+      echo "  FAILED!"
+  else
+      echo "  Passed"
+  fi
+  return_val=`expr $status + $return_val`
+fi
+
+$ECHO_N "Testing 1_8/FORTRAN/H5G/h5ex_g_visit_F03...$ECHO_C"
+if test -f h5ex_g_visit.h5
+then
+    exout ./h5ex_g_visit_F03 >tmp.test
+else
+    cp $srcdir/h5ex_g_visit.h5 h5ex_g_visit.h5
+    exout ./h5ex_g_visit_F03 >tmp.test
+    rm  -f h5ex_g_visit.h5
+fi
+cmp -s tmp.test $srcdir/testfiles/h5ex_g_visit_F03.tst
+status=$?
+if test $status -ne 0
+then
+    echo "  FAILED!"
+else
+    echo "  Passed"
+fi
+return_val=`expr $status + $return_val`
+
+fi
 
 rm -f tmp.test
-echo "$return_val tests failed in 1_10/FORTRAN/H5G/"
+echo "$return_val tests failed in 1_8/FORTRAN/H5G/"
 exit $return_val
diff --git a/1_8/FORTRAN/H5T/test.sh.in b/1_8/FORTRAN/H5T/test.sh.in
--- a/1_8/FORTRAN/H5T/test.sh.in
+++ b/1_8/FORTRAN/H5T/test.sh.in
@@ -13,6 +13,8 @@
 # http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
 # access to either file, you may request a copy from help@hdfgroup.org.
 
+srcdir=@srcdir@
+
 
 case $FC in
 */*)    H5DUMP=`echo $FC | sed -e 's/\/[^/]*$/\/h5dump/'`;
@@ -38,19 +40,23 @@ dumpout() {
     $H5DUMP $*
 }
 
+topics="vlstring"
 
-topics="arrayatt_F03 array_F03 bitatt_F03 bit_F03 cmpdatt_F03 cmpd_F03 \
-Cstring_F03 enumatt_F03 enum_F03 floatatt_F03 float_F03 \
-intatt_F03 int_F03 objrefatt_F03 objref_F03 opaqueatt_F03 opaque_F03 regrefatt_F03 \
-regref_F03 string_F03 vlenatt_F03 vlen_F03 vlstring"
-
+if ($FC -showconfig 2>&1 | grep 'Fortran 2003 Compiler: yes') > /dev/null; then
+  topics="$topics arrayatt_F03 array_F03 bitatt_F03 bit_F03 \
+  cmpdatt_F03 cmpd_F03  enumatt_F03 \
+  enum_F03 floatatt_F03 float_F03 intatt_F03 int_F03 \
+  objrefatt_F03 objref_F03 opaqueatt_F03 opaque_F03 \
+  regrefatt_F03 regref_F03 stringCatt_F03 stringC_F03 \
+  string_F03 vlenatt_F03 vlen_F03"
+fi
 
 return_val=0
 
 for topic in $topics
 do
     fname=h5ex_t_$topic
-    $ECHO_N "Testing 1_10/FORTRAN/H5T/$fname...$ECHO_C"
+    $ECHO_N "Testing 1_8/FORTRAN/H5T/$fname...$ECHO_C"
     exout ./$fname >tmp.test
     cmp -s tmp.test $srcdir/testfiles/$fname.tst
     status=$?
@@ -59,15 +65,15 @@ do
         echo "  FAILED!"
     else
         dumpout $fname.h5 >tmp.test
-    rm -f $fname.h5
+      rm -f $fname.h5
       cmp -s tmp.test $srcdir/testfiles/$fname.ddl
-    status=$?
-    if test $status -ne 0
-    then
-        echo "  FAILED!"
-    else
-        echo "  Passed"
-    fi
+      status=$?
+      if test $status -ne 0
+      then
+          echo "  FAILED!"
+      else
+          echo "  Passed"
+      fi
     fi
     return_val=`expr $status + $return_val`
 done
@@ -76,7 +82,7 @@ done
 #######Non-standard tests#######
 
 #fname=h5ex_t_cpxcmpd
-#$ECHO_N "Testing 1_10/C/H5T/$fname...$ECHO_C"
+#$ECHO_N "Testing 1_8/C/H5T/$fname...$ECHO_C"
 #exout ./$fname >tmp.test
 #cmp -s tmp.test $srcdir/testfiles/$fname.tst
 #status=$?
@@ -85,21 +91,21 @@ done
 #    echo "  FAILED!"
 #else
 #  dumpout -n $fname.h5 >tmp.test
-#rm -f $fname.h5
+#  rm -f $fname.h5
 #  cmp -s tmp.test $srcdir/testfiles/$fname.ddl
-#status=$?
-#if test $status -ne 0
-#then
-#    echo "  FAILED!"
-#else
-#    echo "  Passed"
-#fi
+#  status=$?
+#  if test $status -ne 0
+#  then
+#      echo "  FAILED!"
+#  else
+#      echo "  Passed"
+#  fi
 #fi
 #return_val=`expr $status + $return_val`
 
 
 #fname=h5ex_t_cpxcmpdatt
-#$ECHO_N "Testing 1_10/C/H5T/$fname...$ECHO_C"
+#$ECHO_N "Testing 1_8/C/H5T/$fname...$ECHO_C"
 #exout ./$fname >tmp.test
 #cmp -s tmp.test $srcdir/testfiles/$fname.tst
 #status=$?
@@ -108,21 +114,21 @@ done
 #    echo "  FAILED!"
 #else
 #  dumpout -n $fname.h5 >tmp.test
-#rm -f $fname.h5
+#  rm -f $fname.h5
 #  cmp -s tmp.test $srcdir/testfiles/$fname.ddl
-#status=$?
-#if test $status -ne 0
-#then
-#    echo "  FAILED!"
-#else
-#    echo "  Passed"
-#fi
+#  status=$?
+#  if test $status -ne 0
+#  then
+#      echo "  FAILED!"
+#  else
+#      echo "  Passed"
+#  fi
 #fi
 #return_val=`expr $status + $return_val`
 
 
 #fname=h5ex_t_convert
-#$ECHO_N "Testing 1_10/C/H5T/$fname...$ECHO_C"
+#$ECHO_N "Testing 1_8/C/H5T/$fname...$ECHO_C"
 #exout ./$fname >tmp.test
 #cmp -s tmp.test $srcdir/$fname.test
 #status=$?
@@ -136,5 +142,5 @@ done
 
 
 rm -f tmp.test
-echo "$return_val tests failed in 1_10/FORTRAN/H5T/"
+echo "$return_val tests failed in 1_8/FORTRAN/H5T/"
 exit $return_val
