working with develop

diff --git a/vers/1_6/C/H5T/test.sh.in b/vers/1_6/C/H5T/test.sh.in
--- a/vers/1_6/C/H5T/test.sh.in
+++ b/vers/1_6/C/H5T/test.sh.in
@@ -15,6 +15,7 @@
 
 srcdir=@srcdir@
 
+VER_DIR=$(echo $(basename $(dirname $(dirname $PWD))))
 
 case $CC in
 */*)    H5DUMP=`echo $CC | sed -e 's/\/[^/]*$/\/h5dump/'`;
@@ -33,35 +34,17 @@ ECHO_N="echo $ECHO_N"
 
 
 exout() {
-    echo '*******************************'
-    echo '*  Output of example program  *'
-    echo '*******************************'
-    echo
     $*
 }
 
 dumpout() {
-    echo '**********************'
-    echo '*  Output of h5dump  *'
-    echo '**********************'
-    echo
-    $H5DUMP $*
-}
-
-dumpout2() {
-    echo
-    echo
-    echo '**********************'
-    echo '*  Output of h5dump  *'
-    echo '**********************'
-    echo
     $H5DUMP $*
 }
 
 
 topics="int intatt float floatatt enum enumatt bit bitatt opaque opaqueatt \
 array arrayatt vlen vlenatt string stringatt vlstring vlstringatt \
-cmpd cmpdatt objref objrefatt regref regrefatt"
+cmpd cmpdatt"
 
 
 return_val=0
@@ -70,17 +53,24 @@ return_val=0
 for topic in $topics
 do
     fname=h5ex_t_$topic
-    $ECHO_N "Testing 1_6/C/H5T/$fname...$ECHO_C"
+    $ECHO_N "Testing $VER_DIR/C/H5T/$fname...$ECHO_C"
     exout ./$fname >tmp.test
-    dumpout2 $fname.h5 >>tmp.test
-    rm -f $fname.h5
-    cmp -s tmp.test $srcdir/$fname.test
+    cmp -s tmp.test $srcdir/testfiles/$fname.tst
     status=$?
     if test $status -ne 0
     then
         echo "  FAILED!"
     else
-        echo "  Passed"
+      dumpout $fname.h5 >tmp.test
+      rm -f $fname.h5
+      cmp -s tmp.test $srcdir/testfiles/$fname.ddl
+      status=$?
+      if test $status -ne 0
+      then
+          echo "  FAILED!"
+      else
+          echo "  Passed"
+      fi
     fi
     return_val=`expr $status + $return_val`
 done
@@ -89,41 +79,55 @@ done
 #######Non-standard tests#######
 
 fname=h5ex_t_cpxcmpd
-$ECHO_N "Testing 1_6/C/H5T/$fname...$ECHO_C"
+$ECHO_N "Testing $VER_DIR/C/H5T/$fname...$ECHO_C"
 exout ./$fname >tmp.test
-dumpout2 -n $fname.h5 >>tmp.test
-rm -f $fname.h5
-cmp -s tmp.test $srcdir/$fname.test
+cmp -s tmp.test $srcdir/testfiles/$fname.tst
 status=$?
 if test $status -ne 0
 then
     echo "  FAILED!"
 else
-    echo "  Passed"
+  dumpout -n $fname.h5 >tmp.test
+  rm -f $fname.h5
+  cmp -s tmp.test $srcdir/testfiles/$fname.ddl
+  status=$?
+  if test $status -ne 0
+  then
+      echo "  FAILED!"
+  else
+      echo "  Passed"
+  fi
 fi
 return_val=`expr $status + $return_val`
 
 
 fname=h5ex_t_cpxcmpdatt
-$ECHO_N "Testing 1_6/C/H5T/$fname...$ECHO_C"
+$ECHO_N "Testing $VER_DIR/C/H5T/$fname...$ECHO_C"
 exout ./$fname >tmp.test
-dumpout2 -n $fname.h5 >>tmp.test
-rm -f $fname.h5
-cmp -s tmp.test $srcdir/$fname.test
+cmp -s tmp.test $srcdir/testfiles/$fname.tst
 status=$?
 if test $status -ne 0
 then
     echo "  FAILED!"
 else
-    echo "  Passed"
+  dumpout -n $fname.h5 >tmp.test
+  rm -f $fname.h5
+  cmp -s tmp.test $srcdir/testfiles/$fname.ddl
+  status=$?
+  if test $status -ne 0
+  then
+      echo "  FAILED!"
+  else
+      echo "  Passed"
+  fi
 fi
 return_val=`expr $status + $return_val`
 
 
 fname=h5ex_t_convert
-$ECHO_N "Testing 1_6/C/H5T/$fname...$ECHO_C"
+$ECHO_N "Testing $VER_DIR/C/H5T/$fname...$ECHO_C"
 exout ./$fname >tmp.test
-cmp -s tmp.test $srcdir/$fname.test
+cmp -s tmp.test $srcdir/testfiles/$fname.tst
 status=$?
 if test $status -ne 0
 then
@@ -133,7 +137,43 @@ else
 fi
 return_val=`expr $status + $return_val`
 
+topics="objref objrefatt regref regrefatt"
+
+VERS=""
+CHCK_HDF5VER=`$CC -showconfig | grep -i "HDF5 Version:" | sed 's/^.* //g' | sed 's/[-].*//g'`
+function version_gt { 
+     test "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1"; 
+}
+if version_gt $CHCK_HDF5VER "1.8"; then
+   VERS="110"  
+fi
+
+return_val=0
+for topic in $topics
+do
+    fname=h5ex_t_$topic
+    $ECHO_N "Testing $VER_DIR/C/H5T/$fname...$ECHO_C"
+    exout ./$fname >tmp.test
+    cmp -s tmp.test $srcdir/testfiles/$fname.tst
+    status=$?
+    if test $status -ne 0
+    then
+        echo "  FAILED!"
+    else
+      dumpout $fname.h5 >tmp.test
+      rm -f $fname.h5
+      cmp -s tmp.test $srcdir/testfiles/$fname$VERS.ddl
+      status=$?
+      if test $status -ne 0
+      then
+          echo "  FAILED!"
+      else
+          echo "  Passed"
+      fi
+    fi
+    return_val=`expr $status + $return_val`
+done
 
 rm -f tmp.test
-echo "$return_val tests failed in 1_6/C/H5T/"
+echo "$return_val tests failed in $VER_DIR/C/H5T/"
 exit $return_val
